[package]
name = "less-sync-core"
version = "0.1.0"
edition = "2021"

[dependencies]
less-crypto = { path = "../less-crypto" }
ciborium = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
