[package]
name = "less-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
less-crypto = { path = "../less-crypto" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
